-- ===============================================
-- 003_books.sql
-- Seed initial books and authors data
-- ===============================================

-- Insert authors first (books reference authors through book_authors junction table)
INSERT INTO authors(first_name, last_name, birth_date, death_date)
VALUES
    ('George', 'Orwell', '1903-06-25', '1950-01-21'),
    ('Jane', 'Austen', '1775-12-16', '1817-07-18'),
    ('F. Scott', 'Fitzgerald', '1896-09-24', '1940-12-21'),
    ('Harper', 'Lee', '1926-04-28', '2016-02-19'),
    ('J.D.', 'Salinger', '1919-01-01', '2010-01-27'),
    ('J.R.R.', 'Tolkien', '1892-01-03', '1973-09-02'),
    ('J.K.', 'Rowling', '1965-07-31', NULL),
    ('Ernest', 'Hemingway', '1899-07-21', '1961-07-02'),
    ('Virginia', 'Woolf', '1882-01-25', '1941-03-28'),
    ('Gabriel', 'García Márquez', '1927-03-06', '2014-04-17'),
    ('Toni', 'Morrison', '1931-02-18', '2019-08-05'),
    ('Maya', 'Angelou', '1928-04-04', '2014-05-28'),
    ('Isaac', 'Asimov', '1920-01-02', '1992-04-06'),
    ('Ray', 'Bradbury', '1920-08-22', '2012-06-05'),
    ('Agatha', 'Christie', '1890-09-15', '1976-01-12')
ON CONFLICT DO NOTHING;

-- Insert books
-- Note: The search_vector will be automatically generated by the trigger
-- The updated_at will be automatically set by the trigger
-- Using WHERE NOT EXISTS to handle duplicates since ON CONFLICT doesn't work with partial unique indexes
-- Cover image URLs are from Google Books API
INSERT INTO books(title, isbn_10, isbn_13, genre, publication_date, description, cover_image_url)
SELECT * FROM (VALUES
    -- Classic Literature
    ('1984', '0452284236', '9780452284234', 'Dystopian Fiction', '1949-06-08'::DATE, 
     'A dystopian social science fiction novel and cautionary tale about the dangers of totalitarianism. The story follows Winston Smith, a low-ranking member of the ruling Party in London, who begins to question the Party and its leader, Big Brother.',
     NULL),
    
    ('Pride and Prejudice', '0141439513', '9780141439518', 'Romance', '1813-01-28'::DATE,
     'A romantic novel of manners that follows the character development of Elizabeth Bennet, the dynamic protagonist who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.',
     NULL),
    
    ('The Great Gatsby', '0743273567', '9780743273565', 'Fiction', '1925-04-10'::DATE,
     'A classic American novel set in the Jazz Age, following Nick Carraway as he becomes drawn into the world of his mysterious neighbor Jay Gatsby and his obsession with Daisy Buchanan.',
     NULL),
    
    ('To Kill a Mockingbird', '0061120081', '9780061120084', 'Fiction', '1960-07-11'::DATE,
     'A gripping tale of racial injustice and childhood innocence, told through the eyes of Scout Finch as her father, Atticus Finch, defends a Black man falsely accused of rape in 1930s Alabama.',
     'https://books.google.com/books/content?id=ncuX8p2xLIUC&printsec=frontcover&img=1&source=gbs_api'),
    
    ('The Catcher in the Rye', '0316769177', '9780316769174', 'Fiction', '1951-07-16'::DATE,
     'A controversial novel following Holden Caulfield, a teenager who has been expelled from prep school, as he wanders around New York City and reflects on his experiences.',
     'https://books.google.com/books/content?id=UdnSAAAAMAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    -- Fantasy
    ('The Hobbit', '054792822X', '9780547928227', 'Fantasy', '1937-09-21'::DATE,
     'A fantasy novel about the adventures of hobbit Bilbo Baggins, who is hired by a group of dwarves to help them reclaim their mountain home from the dragon Smaug.',
     'https://books.google.com/books/content?id=LLSpngEACAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('The Lord of the Rings: The Fellowship of the Ring', '0547928211', '9780547928210', 'Fantasy', '1954-07-29'::DATE,
     'The first volume of J.R.R. Tolkien''s epic fantasy trilogy, following Frodo Baggins and the Fellowship as they begin their quest to destroy the One Ring.',
     'https://books.google.com/books/content?id=pVRUswEACAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('Harry Potter and the Philosopher''s Stone', '0747532699', '9780747532699', 'Fantasy', '1997-06-26'::DATE,
     'The first book in the Harry Potter series, following a young wizard as he discovers his magical heritage and begins his education at Hogwarts School of Witchcraft and Wizardry.',
     'https://books.google.com/books/content?id=xYotngEACAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    -- Literary Fiction
    ('The Old Man and the Sea', '0684801221', '9780684801223', 'Fiction', '1952-09-01'::DATE,
     'A short novel about an aging Cuban fisherman who struggles with a giant marlin far out in the Gulf Stream off the coast of Cuba.',
     'https://books.google.com/books/content?id=0rUwAQAAMAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('Mrs. Dalloway', '0156628708', '9780156628709', 'Fiction', '1925-05-14'::DATE,
     'A modernist novel that follows Clarissa Dalloway, a high-society woman in post-World War I England, as she prepares for a party she will host that evening.',
     'https://books.google.com/books/content?id=33ZbAAAAMAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('One Hundred Years of Solitude', '0060883286', '9780060883287', 'Magical Realism', '1967-05-30'::DATE,
     'A landmark novel that tells the multi-generational story of the Buendía family, whose patriarch, José Arcadio Buendía, founds the town of Macondo.',
     'https://books.google.com/books/content?id=Rtk8PgAACAAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('Beloved', '1400033411', '9781400033416', 'Fiction', '1987-09-02'::DATE,
     'A powerful novel about Sethe, a former slave who is haunted by the ghost of her dead daughter, exploring themes of slavery, trauma, and the search for freedom.',
     'https://books.google.com/books/content?id=Ann5ugJilcMC&printsec=frontcover&img=1&source=gbs_api'),
    
    ('I Know Why the Caged Bird Sings', '0345514408', '9780345514400', 'Autobiography', '1969-01-01'::DATE,
     'The first of seven autobiographical works by Maya Angelou, chronicling her childhood and early adult experiences, including her rape at age eight and her journey to find her voice.',
     'https://books.google.com/books/content?id=-BKNEAAAQBAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    -- Science Fiction
    ('Foundation', '0553293354', '9780553293357', 'Science Fiction', '1951-05-01'::DATE,
     'The first book in Isaac Asimov''s Foundation series, following mathematician Hari Seldon as he develops psychohistory to predict the future of humanity and attempts to save civilization from a dark age.',
     'https://books.google.com/books/content?id=Gf6NEAAAQBAJ&printsec=frontcover&img=1&source=gbs_api'),
    
    ('Fahrenheit 451', '1451673310', '9781451673319', 'Dystopian Fiction', '1953-10-19'::DATE,
     'A dystopian novel about a future American society where books are outlawed and "firemen" burn any that are found, following fireman Guy Montag as he begins to question his role.',
     'https://books.google.com/books/content?id=y3CyRurE7P4C&printsec=frontcover&img=1&source=gbs_api'),
    
    -- Mystery
    ('Murder on the Orient Express', '0062693662', '9780062693662', 'Mystery', '1934-01-01'::DATE,
     'A Hercule Poirot mystery novel in which the famous detective must solve a murder aboard the luxurious Orient Express train.',
     'https://books.google.com/books/content?id=rVh7nQAACAAJ&printsec=frontcover&img=1&source=gbs_api')
) AS v(title, isbn_10, isbn_13, genre, publication_date, description, cover_image_url)
WHERE NOT EXISTS (
    SELECT 1 FROM books b 
    WHERE b.isbn_13 = v.isbn_13 AND b.isbn_13 IS NOT NULL
);

-- Link books to authors through book_authors junction table
-- Using subqueries to match by title and author name
INSERT INTO book_authors(book_id, author_id)
SELECT b.id, a.id
FROM books b
CROSS JOIN authors a
WHERE 
    -- 1984
    (b.title = '1984' AND a.first_name = 'George' AND a.last_name = 'Orwell') OR
    -- Pride and Prejudice
    (b.title = 'Pride and Prejudice' AND a.first_name = 'Jane' AND a.last_name = 'Austen') OR
    -- The Great Gatsby
    (b.title = 'The Great Gatsby' AND a.first_name = 'F. Scott' AND a.last_name = 'Fitzgerald') OR
    -- To Kill a Mockingbird
    (b.title = 'To Kill a Mockingbird' AND a.first_name = 'Harper' AND a.last_name = 'Lee') OR
    -- The Catcher in the Rye
    (b.title = 'The Catcher in the Rye' AND a.first_name = 'J.D.' AND a.last_name = 'Salinger') OR
    -- The Hobbit
    (b.title = 'The Hobbit' AND a.first_name = 'J.R.R.' AND a.last_name = 'Tolkien') OR
    -- The Fellowship of the Ring
    (b.title = 'The Lord of the Rings: The Fellowship of the Ring' AND a.first_name = 'J.R.R.' AND a.last_name = 'Tolkien') OR
    -- Harry Potter
    (b.title = 'Harry Potter and the Philosopher''s Stone' AND a.first_name = 'J.K.' AND a.last_name = 'Rowling') OR
    -- The Old Man and the Sea
    (b.title = 'The Old Man and the Sea' AND a.first_name = 'Ernest' AND a.last_name = 'Hemingway') OR
    -- Mrs. Dalloway
    (b.title = 'Mrs. Dalloway' AND a.first_name = 'Virginia' AND a.last_name = 'Woolf') OR
    -- One Hundred Years of Solitude
    (b.title = 'One Hundred Years of Solitude' AND a.first_name = 'Gabriel' AND a.last_name = 'García Márquez') OR
    -- Beloved
    (b.title = 'Beloved' AND a.first_name = 'Toni' AND a.last_name = 'Morrison') OR
    -- I Know Why the Caged Bird Sings
    (b.title = 'I Know Why the Caged Bird Sings' AND a.first_name = 'Maya' AND a.last_name = 'Angelou') OR
    -- Foundation
    (b.title = 'Foundation' AND a.first_name = 'Isaac' AND a.last_name = 'Asimov') OR
    -- Fahrenheit 451
    (b.title = 'Fahrenheit 451' AND a.first_name = 'Ray' AND a.last_name = 'Bradbury') OR
    -- Murder on the Orient Express
    (b.title = 'Murder on the Orient Express' AND a.first_name = 'Agatha' AND a.last_name = 'Christie')
ON CONFLICT (book_id, author_id) DO NOTHING;

-- Log seed completion
DO $$
BEGIN
    RAISE NOTICE '✓ Books and authors seeded successfully';
    RAISE NOTICE '  - Authors inserted: %', (SELECT COUNT(*) FROM authors);
    RAISE NOTICE '  - Books inserted: %', (SELECT COUNT(*) FROM books);
    RAISE NOTICE '  - Book-author relationships: %', (SELECT COUNT(*) FROM book_authors);
END $$;